FROM maven:3-openjdk-17 AS builder

LABEL authors="sebastiaofidencio"

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM openjdk:17-alpine AS config-service

RUN apk update && apk add --no-cache curl vim bash iputils htop

WORKDIR /app

ARG JAR_FILE=gateway-service*.jar

COPY --from=builder /app/gateway-service/target/${JAR_FILE} app.jar

ENV DOCKERIZE_VERSION v0.6.1

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz


EXPOSE 8081

ENTRYPOINT ["dockerize", "-wait", "tcp://discovery-service:8761", "-timeout", "1m", "java", "-jar", "app.jar"]
