name: Setup Java
description: Set up JDK 17
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV