name: Open Pull Request

    on:
      workflow_run:
        workflows: ["CI/CD pipeline for Multi-Module Project in develop"]
        types:
          - completed

    jobs:
      open-pull-request:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Create Pull Request
            uses: peter-evans/create-pull-request@v4
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              commit-message: "Create Pull Request for feature branch"
              branch: ${{ github.event.workflow_run.head_branch }}
              base: develop
              title: "Pull Request for feature branch"
              body: "This PR is automatically created by the CI workflow."